import type { LifePathTemplate } from "@/types";

export const LIFE_PATH_TEMPLATES: LifePathTemplate[] = [
  {
    id: "blank",
    title: "Start from scratch",
    description: "Build your own life plan from a blank canvas. Add custom events to map out your path.",
    nodes: [
      {
        id: "blank-root",
        type: "root",
        label: "My life plan",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Start here and add events that represent your financial decisions and life changes.",
      },
    ],
    edges: [],
  },
  {
    id: "job-loss",
    title: "Recovering from job loss",
    description: "Compare cutting costs plus side income, burning savings, or investing in a career pivot.",
    nodes: [
      {
        id: "jl-root",
        type: "root",
        label: "Job loss",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "A sudden income drop means we need a plan that balances cash protection and recovery speed.",
      },
      {
        id: "jl-dec1",
        type: "decision",
        label: "Your main strategy",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Pick the path that best matches your bandwidth, savings cushion, and support system.",
      },
      {
        id: "jl-cut-gig",
        type: "outcome",
        label: "Cut costs plus gig or temp work",
        monthlyIncomeDelta: 900,
        monthlyExpenseDelta: 200,
        monthsToStability: 8,
        summary: "Bridge the gap with fast income while trimming spending enough to protect cash reserves.",
        milestoneTemplates: [
          {
            phase: "now",
            title: "List your must-pay bills and immediate income options",
            detail: "Lock in housing, food, transport, and any temp or gig leads you can activate this week.",
          },
          {
            phase: "next30",
            title: "Set a weekly job-search and side-income target",
            detail: "Keep your main search moving while tracking how much the side work actually closes the gap.",
          },
        ],
      },
      {
        id: "jl-savings",
        type: "outcome",
        label: "Rely on savings while job searching",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: -18,
        summary: "Savings buy time, but the plan depends on runway discipline and a clear stop-loss point.",
        milestoneTemplates: [
          {
            phase: "now",
            title: "Calculate exactly how many months your savings can cover",
            detail: "Use your current bills, not ideal spending, so your runway estimate stays realistic.",
          },
          {
            phase: "next30",
            title: "Set a runway checkpoint and backup plan",
            detail: "Choose the month when you will switch to deeper cuts, benefits, or bridge income if hiring takes longer.",
          },
        ],
      },
      {
        id: "jl-retrain",
        type: "outcome",
        label: "Retrain or pivot careers",
        monthlyIncomeDelta: -400,
        monthlyExpenseDelta: 350,
        monthsToStability: 16,
        summary: "A longer path that can improve future income, but it needs a strict transition budget.",
        milestoneTemplates: [
          {
            phase: "now",
            title: "Price the pivot before committing",
            detail: "Write down tuition, software, transport, and the income dip so the change is fully visible.",
          },
          {
            phase: "oneToThreeMonths",
            title: "Review progress against the pivot timeline",
            detail: "Check whether coursework, certificates, or applications are actually improving your next-income odds.",
          },
        ],
      },
    ],
    edges: [
      { id: "jl-e0", from: "jl-root", to: "jl-dec1", risk: "stable" },
      { id: "jl-e1", from: "jl-dec1", to: "jl-cut-gig", risk: "stable" },
      { id: "jl-e2", from: "jl-dec1", to: "jl-savings", risk: "crisis" },
      { id: "jl-e3", from: "jl-dec1", to: "jl-retrain", risk: "risky" },
    ],
  },
  {
    id: "emergency-fund",
    title: "Building first emergency fund",
    description: "See how different monthly savings rates change your timeline and flexibility.",
    nodes: [
      {
        id: "ef-root",
        type: "root",
        label: "Start building",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Even a small recurring contribution can turn surprise costs into manageable setbacks.",
      },
      {
        id: "ef-dec1",
        type: "decision",
        label: "Monthly savings target",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Choose a target you can actually keep through good and bad months.",
      },
      {
        id: "ef-200",
        type: "outcome",
        label: "Save $200 per month",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 200,
        monthsToStability: 10,
        summary: "Fast progress if your budget can absorb it without causing bounce-back spending later.",
        milestoneTemplates: [
          {
            phase: "now",
            title: "Move the first contribution automatically",
            detail: "Automation makes the plan durable and removes the need to decide every month.",
          },
          {
            phase: "next30",
            title: "Protect the contribution from category creep",
            detail: "If this target feels tight, trim one category instead of abandoning the whole goal.",
          },
        ],
      },
      {
        id: "ef-50",
        type: "outcome",
        label: "Save $50 per month",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 50,
        monthsToStability: 18,
        summary: "A steadier pace that may be easier to maintain during uneven months.",
        milestoneTemplates: [
          {
            phase: "now",
            title: "Choose the account and transfer day",
            detail: "Make the habit visible so you can tell quickly if the plan is slipping.",
          },
          {
            phase: "oneToThreeMonths",
            title: "Review whether you can increase the target",
            detail: "A modest bump later often works better than setting an aggressive number too early.",
          },
        ],
      },
      {
        id: "ef-15",
        type: "outcome",
        label: "Save $15 per month",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 15,
        monthsToStability: 28,
        summary: "A small start is still a real plan when cash flow is fragile.",
        milestoneTemplates: [
          {
            phase: "now",
            title: "Start with the smallest automatic transfer that feels safe",
            detail: "Consistency matters more than the opening amount when you are building the habit.",
          },
          {
            phase: "later",
            title: "Define the trigger for raising the contribution",
            detail: "Tie your next increase to a raise, debt payoff, lower rent, or another concrete change.",
          },
        ],
      },
    ],
    edges: [
      { id: "ef-e0", from: "ef-root", to: "ef-dec1", risk: "stable" },
      { id: "ef-e1", from: "ef-dec1", to: "ef-200", risk: "stable" },
      { id: "ef-e2", from: "ef-dec1", to: "ef-50", risk: "risky" },
      { id: "ef-e3", from: "ef-dec1", to: "ef-15", risk: "risky" },
    ],
  },
  {
    id: "debt",
    title: "Getting out of debt",
    description: "Snowball vs avalanche vs minimum payments - modeled impact on cash flow.",
    nodes: [
      {
        id: "db-root",
        type: "root",
        label: "Debt payoff",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Your payment strategy changes both monthly breathing room and long-term cost.",
      },
      {
        id: "db-dec1",
        type: "decision",
        label: "Strategy",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Choose between momentum, interest savings, or short-term flexibility.",
      },
      {
        id: "db-snowball",
        type: "outcome",
        label: "Snowball (smallest first)",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 320,
        monthsToStability: 14,
        summary: "Build motivation with early wins, even if it is not always the mathematically cheapest route.",
        milestoneTemplates: [
          {
            phase: "now",
            title: "Order your balances from smallest to largest",
            detail: "Define the exact first account that gets every extra dollar so the plan stays simple.",
          },
          {
            phase: "next30",
            title: "Redirect each paid-off amount into the next balance",
            detail: "Keep the payment rolling forward instead of letting the freed cash disappear into other spending.",
          },
        ],
      },
      {
        id: "db-avalanche",
        type: "outcome",
        label: "Avalanche (highest APR)",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 340,
        monthsToStability: 12,
        summary: "Costs more each month now, but usually reduces interest drag the fastest.",
        milestoneTemplates: [
          {
            phase: "now",
            title: "Rank debts by APR and confirm minimums",
            detail: "You need the interest order and minimum payment amounts in one place before executing the plan.",
          },
          {
            phase: "oneToThreeMonths",
            title: "Check whether the highest-rate debt is shrinking as expected",
            detail: "If the balance is not moving, revisit the payment amount or fees dragging progress.",
          },
        ],
      },
      {
        id: "db-min",
        type: "outcome",
        label: "Minimum payments only",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 110,
        monthsToStability: 42,
        summary: "Preserves short-term flexibility, but keeps the debt burden around much longer.",
        milestoneTemplates: [
          {
            phase: "now",
            title: "Use the lower payment to stabilize the rest of your budget",
            detail: "This path only works if the extra room prevents new missed bills or new debt.",
          },
          {
            phase: "later",
            title: "Choose the signal for moving to a stronger payoff plan",
            detail: "Set the income, savings, or expense-change target that lets you step up from minimums.",
          },
        ],
      },
    ],
    edges: [
      { id: "db-e0", from: "db-root", to: "db-dec1", risk: "stable" },
      { id: "db-e1", from: "db-dec1", to: "db-snowball", risk: "stable" },
      { id: "db-e2", from: "db-dec1", to: "db-avalanche", risk: "stable" },
      { id: "db-e3", from: "db-dec1", to: "db-min", risk: "crisis" },
    ],
  },
  {
    id: "medical-bills",
    title: "Managing medical bills",
    description: "Navigate unexpected health costs with negotiation, payment plans, and assistance programs.",
    nodes: [
      {
        id: "mb-root",
        type: "root",
        label: "Medical bills hit",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Unexpected medical costs require quick action on billing, insurance, and payment options.",
      },
      {
        id: "mb-dec1",
        type: "decision",
        label: "Payment approach",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Choose how to manage the bills based on your insurance status and cash position.",
      },
      {
        id: "mb-negotiate",
        type: "outcome",
        label: "Negotiate and payment plan",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 150,
        monthsToStability: 12,
        summary: "Request itemized bills, dispute errors, negotiate down, then set up 0% payment plans.",
        milestoneTemplates: [
          { phase: "now", title: "Request itemized bill and check for errors", detail: "Call billing, ask for line-by-line breakdown. Errors are common and can reduce the total significantly." },
          { phase: "next30", title: "Set up a manageable payment plan", detail: "Most providers offer 0% interest plans. Even $25/month keeps accounts out of collections." },
        ],
      },
      {
        id: "mb-assistance",
        type: "outcome",
        label: "Apply for financial assistance",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 50,
        monthsToStability: 6,
        summary: "Hospitals receiving federal funding must offer charity care. Check Medicaid retroactive coverage.",
        milestoneTemplates: [
          { phase: "now", title: "Apply for hospital financial assistance", detail: "Ask for the charity care application. Many hospitals write off bills for patients under 200-400% of poverty level." },
          { phase: "next30", title: "Check Medicaid retroactive coverage", detail: "In many states, Medicaid covers bills from up to 3 months before application." },
        ],
      },
      {
        id: "mb-credit",
        type: "outcome",
        label: "Use credit or savings",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 300,
        monthsToStability: 18,
        summary: "Fastest resolution but highest long-term cost. Only use if other options are exhausted.",
        milestoneTemplates: [
          { phase: "now", title: "Compare interest rates before using credit", detail: "Hospital payment plans are usually 0%. Credit cards are 20%+. Exhaust other options first." },
          { phase: "oneToThreeMonths", title: "Refinance high-interest medical debt", detail: "Look into medical-specific personal loans or balance transfers if stuck with high-rate credit." },
        ],
      },
    ],
    edges: [
      { id: "mb-e0", from: "mb-root", to: "mb-dec1", risk: "stable" },
      { id: "mb-e1", from: "mb-dec1", to: "mb-negotiate", risk: "stable" },
      { id: "mb-e2", from: "mb-dec1", to: "mb-assistance", risk: "stable" },
      { id: "mb-e3", from: "mb-dec1", to: "mb-credit", risk: "crisis" },
    ],
  },
  {
    id: "eviction",
    title: "Facing eviction or housing loss",
    description: "Explore legal protections, negotiation, relocation, and emergency housing options.",
    nodes: [
      {
        id: "ev-root",
        type: "root",
        label: "Eviction notice",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "An eviction notice is not the same as an eviction. You have legal rights and time to respond.",
      },
      {
        id: "ev-dec1",
        type: "decision",
        label: "Response strategy",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Choose between fighting, negotiating, or planning a strategic move.",
      },
      {
        id: "ev-negotiate",
        type: "outcome",
        label: "Negotiate with landlord",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 3,
        summary: "Many landlords prefer a payment plan over the cost and time of formal eviction.",
        milestoneTemplates: [
          { phase: "now", title: "Contact landlord with a written payment proposal", detail: "Offer a realistic plan. Put everything in writing to protect yourself legally." },
          { phase: "next30", title: "Follow through on first payment and document it", detail: "Keep receipts and written confirmation of every payment to prevent disputes." },
        ],
      },
      {
        id: "ev-legal",
        type: "outcome",
        label: "Seek legal aid and fight",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 100,
        monthsToStability: 6,
        summary: "Free legal aid can buy time and sometimes stop wrongful evictions entirely.",
        milestoneTemplates: [
          { phase: "now", title: "Contact legal aid immediately", detail: "Search lawhelp.org or call 211 for free legal services. Many evictions have procedural defenses." },
          { phase: "next30", title: "Attend court date if required", detail: "Never ignore a court summons. Showing up with legal counsel dramatically improves outcomes." },
        ],
      },
      {
        id: "ev-move",
        type: "outcome",
        label: "Plan a strategic move",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: -200,
        monthsToStability: 4,
        summary: "Moving on your terms is better than being forced out. May reduce long-term housing costs.",
        milestoneTemplates: [
          { phase: "now", title: "Research emergency and transitional housing", detail: "Call 211, check local shelters, and look into rapid rehousing programs in your area." },
          { phase: "next30", title: "Secure new housing before the eviction deadline", detail: "Having a place lined up reduces stress and prevents gaps that damage rental history." },
        ],
      },
    ],
    edges: [
      { id: "ev-e0", from: "ev-root", to: "ev-dec1", risk: "stable" },
      { id: "ev-e1", from: "ev-dec1", to: "ev-negotiate", risk: "stable" },
      { id: "ev-e2", from: "ev-dec1", to: "ev-legal", risk: "risky" },
      { id: "ev-e3", from: "ev-dec1", to: "ev-move", risk: "risky" },
    ],
  },
  {
    id: "car-accident",
    title: "Recovering from a car accident",
    description: "Handle insurance claims, repair costs, medical bills, and income disruption after a collision.",
    nodes: [
      {
        id: "ca-root",
        type: "root",
        label: "Car accident",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "A car accident creates overlapping costs: repairs, medical, transport, and possible lost wages.",
      },
      {
        id: "ca-dec1",
        type: "decision",
        label: "Insurance and repair path",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Your next steps depend on insurance coverage, fault, and vehicle condition.",
      },
      {
        id: "ca-insured",
        type: "outcome",
        label: "File claim and use coverage",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 80,
        monthsToStability: 4,
        summary: "Insurance covers most costs but expect deductibles, rental gaps, and premium increases.",
        milestoneTemplates: [
          { phase: "now", title: "File insurance claim and document everything", detail: "Call your claims line today. Photograph all damage, save the police report number, and track expenses." },
          { phase: "next30", title: "Follow up on claim status and get repair estimates", detail: "Get 2-3 estimates from certified shops. Don't accept the first settlement offer." },
        ],
      },
      {
        id: "ca-uninsured",
        type: "outcome",
        label: "Pay out of pocket",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 350,
        monthsToStability: 10,
        summary: "Without insurance, costs hit hard. Negotiate with shops and explore payment plans.",
        milestoneTemplates: [
          { phase: "now", title: "Get multiple repair estimates and negotiate", detail: "Independent shops are often cheaper than dealerships. Ask about payment plans." },
          { phase: "next30", title: "Arrange temporary transportation", detail: "Look into carpooling, transit passes, or short-term vehicle loans to maintain income." },
        ],
      },
      {
        id: "ca-totaled",
        type: "outcome",
        label: "Vehicle totaled — replace or go carless",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 200,
        monthsToStability: 8,
        summary: "If the car is totaled, decide whether to replace it or restructure around transit.",
        milestoneTemplates: [
          { phase: "now", title: "Get the insurance payout or salvage value", detail: "If totaled, negotiate the total loss payout. Check if gap insurance applies." },
          { phase: "oneToThreeMonths", title: "Decide on replacement vehicle or transit plan", detail: "Compare the cost of a used car payment vs transit/rideshare over 12 months." },
        ],
      },
    ],
    edges: [
      { id: "ca-e0", from: "ca-root", to: "ca-dec1", risk: "stable" },
      { id: "ca-e1", from: "ca-dec1", to: "ca-insured", risk: "stable" },
      { id: "ca-e2", from: "ca-dec1", to: "ca-uninsured", risk: "crisis" },
      { id: "ca-e3", from: "ca-dec1", to: "ca-totaled", risk: "risky" },
    ],
  },
  {
    id: "natural-disaster",
    title: "After a natural disaster",
    description: "Navigate FEMA aid, insurance claims, temporary housing, and rebuilding finances.",
    nodes: [
      {
        id: "nd-root",
        type: "root",
        label: "Disaster strikes",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Natural disasters disrupt housing, income, and daily life simultaneously.",
      },
      {
        id: "nd-dec1",
        type: "decision",
        label: "Recovery path",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 0,
        monthsToStability: 0,
        summary: "Choose based on insurance status, damage level, and available support.",
      },
      {
        id: "nd-fema",
        type: "outcome",
        label: "FEMA aid plus insurance claim",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 200,
        monthsToStability: 8,
        summary: "Combining FEMA assistance with insurance provides the most coverage for rebuilding.",
        milestoneTemplates: [
          { phase: "now", title: "Register with FEMA at disasterassistance.gov", detail: "Apply within 60 days. FEMA can provide housing assistance, repairs, and other needs." },
          { phase: "next30", title: "File insurance claim with full documentation", detail: "Photograph all damage, keep receipts, and submit your claim as soon as possible." },
        ],
      },
      {
        id: "nd-relocate",
        type: "outcome",
        label: "Relocate temporarily or permanently",
        monthlyIncomeDelta: -300,
        monthlyExpenseDelta: 400,
        monthsToStability: 12,
        summary: "Relocation is expensive upfront but may be necessary if the area is unsafe.",
        milestoneTemplates: [
          { phase: "now", title: "Secure temporary housing through Red Cross or FEMA", detail: "Call 211 or visit a local shelter. FEMA may cover hotel costs for displaced families." },
          { phase: "oneToThreeMonths", title: "Decide on permanent relocation or return", detail: "Compare rebuilding costs against starting fresh in a new area." },
        ],
      },
      {
        id: "nd-rebuild",
        type: "outcome",
        label: "Rebuild in place on a budget",
        monthlyIncomeDelta: 0,
        monthlyExpenseDelta: 500,
        monthsToStability: 18,
        summary: "Staying and rebuilding takes longer but preserves community ties and avoids moving costs.",
        milestoneTemplates: [
          { phase: "now", title: "Prioritize safety-critical repairs first", detail: "Focus on structural, electrical, and water damage before cosmetic repairs." },
          { phase: "later", title: "Apply for SBA disaster loans if needed", detail: "SBA offers low-interest loans for disaster recovery. Apply even if you think you won't qualify." },
        ],
      },
    ],
    edges: [
      { id: "nd-e0", from: "nd-root", to: "nd-dec1", risk: "stable" },
      { id: "nd-e1", from: "nd-dec1", to: "nd-fema", risk: "stable" },
      { id: "nd-e2", from: "nd-dec1", to: "nd-relocate", risk: "risky" },
      { id: "nd-e3", from: "nd-dec1", to: "nd-rebuild", risk: "crisis" },
    ],
  },
];

/** Maps crisis page IDs to flow template IDs */
export const CRISIS_TO_TEMPLATE: Record<string, string> = {
  "job-loss": "job-loss",
  "medical-bills": "medical-bills",
  "car-accident": "car-accident",
  "eviction": "eviction",
  "natural-disaster": "natural-disaster",
};

export function getTemplateById(id: string): LifePathTemplate | undefined {
  return LIFE_PATH_TEMPLATES.find((t) => t.id === id);
}

